/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{html,ts}'],
  theme: {
    extend: {},
    screens: {
      handset: { max: '599.98px' },
      tablet: { min: '600px', max: '959.98px' },
      desktop: { min: '960px' },
    },
    fontSize: {
      sm: '13px',
      md: '14px',
      xl: '20px',
    },
    colors: {
      'light-grey': 'var(--light-grey)',
      orange: 'var(--orange-)',
      'grey-strok': 'var(--grey-strok)',
      blue: 'var(--blue)',
      'grey-tab': 'var(--grey-tab)',
      'grey-indicator': 'var(--grey-indicator)',
      'subtitle-grey': 'var(--subtitle-grey)',
      'color-strok': 'var(--color-strok)',
      bkgrnd: 'var(--bkgrnd)',
      'blue-2': 'var(--blue-2)',
      'dark-blue': 'var(--dark-blue)',
      white: 'var(--white)',
      'grey-text': 'var(--grey-text)',
      'light-blue': 'var(--light-blue)',
      'logo-blue': 'var(--logo-blue)',
      black: 'var(--black)',
      'opacity-black': 'var(--opacity-black)',
      'active-orange': 'var(--active-orange)',
      'hover-blue': 'var(--hover-blue)',
      'hover-orange': 'var(--hover-orange)',
      'hover-black': 'var(--hover-black)',
      'active-black': 'var(--active-black)',
      'shadow-grey': 'var(--shadow-grey)',
      'hover-blue': 'var(--hover-blue)',
      transparent: 'transparent',
    },
    fontFamily: {
      gilroy: ['Gilroy', 'sans-serif'],
      inter: ['Inter', 'sans-serif'],
    },
  },
  plugins: [],
}
